server:
  port: 8086

# mysql
spring:
  jackson:
    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  profiles:
    active: test

eris:
  database: mysql

logging:
  level:
    root: info
